### ISSUE TITLE
Migrations under Craft 3.4 failing

### ISSUE THREAD

**Issue by thinkflo** [dgrigg/craft-migration-assistant#20] opened 2020-02-13 09:40 UTC
Currently unable to run migrations of an Entry in Craft 3.4.  Tried a migration of an entry with the following trace stack:

`2020-02-13 10:16:16 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply m200213_095645_migration_entry_kassensystem (time: 2.746s). Output:
Exception: strtolower() expects parameter 1 to be string, array given (/var/www/html/craft/vendor/craftcms/cms/src/helpers/Db.php:445)
#0 /var/www/html/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /var/www/html/craft/vendor/craftcms/cms/src/helpers/Db.php(445): craft\web\ErrorHandler->handleError()
#2 /var/www/html/craft/vendor/craftcms/cms/src/helpers/Db.php(445): ::strtolower()
#3 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1367): craft\helpers\Db::parseParam()
#4 /var/www/html/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\EntryQuery->prepare()
#5 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(146): craft\db\mysql\QueryBuilder->build()
#6 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(429): craft\elements\db\EntryQuery->createCommand()
#7 /var/www/html/craft/vendor/craftcms/cms/src/db/Query.php(214): craft\elements\db\EntryQuery->exists()
#8 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1531): craft\elements\db\EntryQuery->exists()
#9 /var/www/html/craft/vendor/craftcms/cms/src/fields/BaseRelationField.php(340): craft\elements\db\EntryQuery->exists()
#10 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1406): craft\fields\Entries->isValueEmpty()
#11 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1130): craft\elements\MatrixBlock->isFieldEmpty()
#12 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(466): craft\elements\MatrixBlock->__call()
#13 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(466): craft\elements\MatrixBlock->isFieldEmpty:pageSelector()
#14 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(466): ::call_user_func:{/var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php:466}()
#15 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(254): craft\validators\ArrayValidator->isEmpty()
#16 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(367): craft\validators\ArrayValidator->validateAttributes()
#17 /var/www/html/craft/vendor/craftcms/cms/src/fields/Matrix.php(715): craft\elements\MatrixBlock->validate()
#18 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1388): craft\fields\Matrix->validateBlocks()
#19 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): verbb\supertable\elements\SuperTableBlockElement->validateCustomFieldAttribute()
#20 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): ::call_user_func:{/var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php:72}()
#21 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute()
#22 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\InlineValidator->validateAttributes()
#23 /var/www/html/craft/vendor/verbb/super-table/src/fields/SuperTableField.php(673): verbb\supertable\elements\SuperTableBlockElement->validate()
#24 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1388): verbb\supertable\fields\SuperTableField->validateBlocks()
#25 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): craft\elements\MatrixBlock->validateCustomFieldAttribute()
#26 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): ::call_user_func:{/var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php:72}()
#27 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute()
#28 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\InlineValidator->validateAttributes()
#29 /var/www/html/craft/vendor/craftcms/cms/src/fields/Matrix.php(715): craft\elements\MatrixBlock->validate()
#30 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(1388): craft\fields\Matrix->validateBlocks()
#31 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): craft\elements\Entry->validateCustomFieldAttribute()
#32 /var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): ::call_user_func:{/var/www/html/craft/vendor/yiisoft/yii2/validators/InlineValidator.php:72}()
#33 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute()
#34 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\InlineValidator->validateAttributes()
#35 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(1981): craft\elements\Entry->validate()
#36 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal()
#37 /var/www/html/craft/vendor/dgrigg/craft-migration-assistant/src/services/EntriesContent.php(110): craft\services\Elements->saveElement()
#38 /var/www/html/craft/vendor/dgrigg/craft-migration-assistant/src/services/BaseMigration.php(147): dgrigg\migrationassistant\services\EntriesContent->importItem()
#39 /var/www/html/craft/vendor/dgrigg/craft-migration-assistant/src/services/Migrations.php(287): dgrigg\migrationassistant\services\EntriesContent->import()
#40 /var/www/html/craft/migrations/m200213_095645_migration_entry_kassensystem.php(31): dgrigg\migrationassistant\services\Migrations->import()
#41 /var/www/html/craft/vendor/craftcms/cms/src/db/Migration.php(52): craft\contentmigrations\m200213_095645_migration_entry_kassensystem->safeUp()
#42 /var/www/html/craft/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\contentmigrations\m200213_095645_migration_entry_kassensystem->up()
#43 /var/www/html/craft/vendor/dgrigg/craft-migration-assistant/src/services/Migrations.php(335): craft\db\MigrationManager->migrateUp()
#44 /var/www/html/craft/vendor/dgrigg/craft-migration-assistant/src/controllers/RunController.php(111): dgrigg\migrationassistant\services\Migrations->runMigrations()
#45 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): dgrigg\migrationassistant\controllers\RunController->actionMigrations()
#46 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#47 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#48 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(178): dgrigg\migrationassistant\controllers\RunController->runAction()
#49 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(528): dgrigg\migrationassistant\controllers\RunController->runAction()
#50 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(290): craft\web\Application->runAction()
#51 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction()
#52 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest()
#53 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#54 /var/www/html/craft/web/index.php(21): craft\web\Application->run()
#55 {main}`

**Comment by ricricucit** [comment] 2020-02-19 11:52
@dgrigg is this plugin being updated? Asking, because I'm making clients pay for this plugin's license, and therefor the updates..............

**Comment by dgrigg** [comment] 2020-02-19 12:23
@thinkflo @ricricucit I am working on this issue

**Comment by dgrigg** [comment] 2020-02-19 16:49
@thinkflo @ricricucit two questions:

1. which specific version of Craft are you running?

2. Is this happening on section/field or content migrations?

3. Any details you can provide on the type of entry (if it's a content entry) you are attempting to migrate. Any special fields?

**Comment by ricricucit** [comment] 2020-02-20 13:10
Thanks!
TBH with you, I did not yet migrate to 3.4 because I've read about this issue.
I didn't personally experienced it, but I would like not to experience it 😊

**Comment by dgrigg** [comment] 2020-02-20 13:12
@ricricucit which issues on 3.4 did you read about? I have tested with 3.4.6.1 and everything is working correctly. This could be an internal Craft issue.

**Comment by ricricucit** [comment] 2020-02-20 13:14
......this one 😊 

I was just checking all "vital" plugins issues list, before migrating. Reading this issue, stopped me from migrating the project to the latest craft.

Are you saying you cannot reproduce it?

**Comment by dgrigg** [comment] 2020-02-20 13:16
Ahh, I thought you meant an issue on a Craft upgrade list. I have not been able to reproduce this error. Hoping @thinkflo can provide some additional details about his environment.

**Comment by dgrigg** [comment] 2020-02-20 13:18
@thinkflo one idea I just had, the error looks like it's happening with a BaseRelationField. Could you be missing a field in your export that you have set as required on the section?

**Comment by dgrigg** [comment] 2020-02-25 16:48
@thinkflo going to close this issue if you have no additional details to add. I can't replicate this problem, I suspect it's related to your content, not the plugin.

**Comment by ricricucit** [comment] 2020-03-03 14:02
soooooo I guess I can upgrade? 😊

**Comment by dgrigg** [comment] 2020-03-03 14:13
go for it

**Closed by dgrigg** 2020-03-03 14:13 UTC
